name: Pipeline CI CD pour worldreal
on:
    push:
        branches:
            - master
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: Hello GitHub Actions
              run: echo "Hello from Github Actions!"
            - name: Recuperer le code source
              uses: actions/checkout@v4
            - name: lister les fichiers
              run: ls -la

              