name: Pipeline CI CD pour worldreal
on:
    push:
        branches:
            - master
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: Hello GitHub Actions
              run: echo "Hello from Github Actions!"
            - name: Recuperer le code source
              uses: actions/checkout@v4
            - name: lister les fichiers
              run: ls -la
            - name: setup python
              uses: actions/setup-python@v7
              with:
                version: '3.9'
            - name: version python
              run: python --version
            - name: Install poetry
              run: pip install poetry
            - name: install dependancies
              run: poetry --version && poetry install
            - name: lancer le test
              run: poetry run pytest
            

              